CREATE TABLE IF NOT EXISTS ratings (
  rating_id int UNIQUE PRIMARY KEY,
  title varchar
);
CREATE TABLE IF NOT EXISTS genres (
  genre_id int UNIQUE PRIMARY KEY,
  title varchar
);

CREATE TABLE IF NOT EXISTS films (
  film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  description varchar,
  releaseDate date,
  duration int
);

CREATE TABLE IF NOT EXISTS users (
  user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar,
  login varchar,
  name varchar,
  birthday date
);

CREATE TABLE IF NOT EXISTS likes (
  film_id int REFERENCES films (film_id) ON DELETE CASCADE,
  user_id int REFERENCES users (user_id) ON DELETE CASCADE,
  PRIMARY KEY (film_id,user_id)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id int REFERENCES users (user_id) ON DELETE CASCADE,
  friend_id int REFERENCES users (user_id) ON DELETE CASCADE,
  PRIMARY KEY (user_id,friend_id)
);

CREATE TABLE IF NOT EXISTS ratings_films (
film_id int REFERENCES films (film_id) ON DELETE CASCADE,
rating_id int REFERENCES ratings (rating_id) ON DELETE CASCADE,
PRIMARY KEY (film_id,rating_id)
);

CREATE TABLE IF NOT EXISTS genres_films (
film_id int REFERENCES films (film_id) ON DELETE CASCADE,
genre_id int REFERENCES genres (genre_id) ON DELETE CASCADE,
PRIMARY KEY (film_id,genre_id)
);